name: New Modpack Submission
description: Submit a Modpack to the Index!
title: "[Modpack]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your modpack to the index!
  - type: input
    id: modpack-download-link
    attributes:
      label: Modpack Download Link
      description: The download link to your modpack
      validations:
        required: true